[package]
name = "ola_constants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ola_utils = { path = "../utils" }
ola_types = { path = "../types" }
once_cell = "1.13.0"
