[package]
name = "olaos_offchain_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ola_config = { path = "../config" }
olaos_logs = { path = "../logs" }
ola_types = { path = "../types" }
anyhow = "1.0"
tokio = { version = "=1.35.0", features = ["full"] }

