[package]
name = "ola_state"
version = "0.1.0"
edition = "2021"

[dependencies]
ola_types = { path = "../types" }
ola_dal = { path = "../dal" }
olaos_storage = { path = "../storage" }
olaos_logs = { path = "../logs" }
mini-moka = "0.10.0"
tokio = { version = "1", features = ["rt"] }