[env]
OLAOS_IN_DOCKER = "false"
OLAOS_DATABASE_POOL_SIZE = "50"
OLAOS_DATABASE_MULTI_GET_CHUNK_SIZE = "1000"
OLAOS_DATABASE_SEQUENCER_DB_PATH = "./db/main/sequencer"
OLAOS_SEQUENCER_FEE_ACCOUNT_ADDR = "0xde03a0B5963f75f1C8485B355fF6D30f3093BDE7"
OLAOS_SEQUENCER_ENTRYPOINT_HASH = "0xfefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefe"
OLAOS_SEQUENCER_DEFAULT_AA_HASH = "0xfefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefefe"
OLAOS_NETWORK_NETWORK = "localhost"
OLAOS_NETWORK_OLA_NETWORK_ID = "270"
OLAOS_NETWORK_OLA_NETWORK_NAME = "localhost"
OLAOS_WEB3_JSON_RPC_MAX_NONCE_AHEAD = "100"
OLAOS_HEALTHCHECK_PORT = "13002"
OLAOS_MEMPOOL_CAPACITY = "1000000"