[package]
name = "ola_config"
version = "0.1.0"
edition = "2021"

[dependencies]
ola_basic_types ={ path = "../basic_types"}
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
