[package]
name = "ola_basic_types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
web3 = { version= "0.19.0", default-features = false }
olavm_core = {package = "core", git = "https://github.com/Sin7Y/olavm.git"}
hex = "0.4"